routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SeminarController;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\SeminarVideoController;
use App\Http\Controllers\SeminarCertificateController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('Auth.index');
})->name('login');

Route::get('/', function () {
    return view('Auth.register');
})->name('registration');

Route::controller(UserController::class)->group(function () {
	Route::get('registration-verify/{token}','showVerifyEmail')->name('registration_verify.get');
	Route::post('registration','store')->name('registration.store');
    Route::get('registration-success', 'success')->name('registration.success');
});

//Authentications/Login
Route::group(['prefix'=> 'auth'], function(){
	Route::name('auth.')->group(function () {
		// For Login
		Route::controller(AuthController::class)->group(function () {
	 		 Route::post('request', 'authenticate')->name('authenticate');
	 		 Route::get('test', 'test')->name('test');
		});

		// For Forgot Password
		Route::controller(ForgotPasswordController::class)->group(function () {
			Route::get('forget-password', 'index')->name('forget.password.get');
			Route::post('forget-password','store')->name('forget.password.post');
			Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
			Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
			Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
			Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
		});
	});
});


// Route::get('account/', 'AccountController@index')->name('account.index');

Route::group(['prefix'=> 'account', 'middleware' => ['auth']], function(){
    Route::name('account.')->group(function () {
        // Main Manager Page
        Route::controller(AccountController::class)->group(function () {
            Route::get('','index')->name('index');
            Route::get('show/{id?}','showUserAccount')->name('show');
            Route::get('edit/{id?}','editUserAccount')->name('edit');
            Route::post('update/{id?}','update')->name('update');

            Route::post('account/certificate/','uploadCertificate')->name('upload.certificate');
        });
    });


    Route::name('qrcode.')->group(function () {
        // QRcode
        Route::controller(QrCodeController::class)->group(function () {
            Route::get('qrcode-details/{id}/{seminar_id}','index')->name('index');
            Route::get('check-reception/{id}','checkSeminar')->name('check.seminar');
            Route::get('error-reception/{id}','errorSeminar')->name('error.seminar');
            Route::get('in-reception/{id}','inSeminar')->name('in.seminar');
            Route::get('out-reception/{id}','outSeminar')->name('out.seminar');
        });
    });

    Route::name('seminar.')->group(function () {
        // Seminar Pages
        Route::controller(SeminarController::class)->group(function () {
            Route::get('seminar-list/{seminar_group_id}','index')->name('index'); //this would be seminar list
            Route::get('seminar-detail/{id}','show')->name('show');  //this would be seminar detail
            Route::post('seminar-register','register')->name('register');  //this would be seminar registration
            Route::post('seminar-cancel','cancel')->name('cancel');  //this would be cancel of seminar registration
            Route::get('seminar-register-action', 'register_action')->name('register.action');

            Route::get('seminar-user-detail/{id}','user_detail')->name('user.detail');  //this would be user seminar detail

        });
    });

    Route::name('seminar_exam.')->group(function () {
        // Seminar Exam
        Route::controller(ExamController::class)->group(function () {
            Route::get('seminar-exam/{seminar_registration_id}','index')->name('index');
            Route::post('seminar-exam-store/','store')->name('store');
            Route::get('seminar-exam-success/{seminar_registration_id}','success')->name('success');
            Route::post('seminar-on-demand-exam-store/','userOnDemandExamstore')->name('user_on_demand_exam.store');
        });
    });


    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

});

// video on demand
Route::group(['prefix'=> 'seminar-video', 'as' => 'SeminarVideo.', 'middleware' => ['auth']], function(){
    Route::controller(SeminarVideoController::class)->group(function () {
        Route::get('','index')->name('index');
        Route::get('start-video/{seminar_id}','start_video')->name('start');
        Route::get('save-video/{seminar_id}','save_video')->name('save.video');
        Route::get('play-video/{user_ondemand_history_id}','play_video')->name('play.video');
        Route::get('exam/{user_ondemand_history_id}/{video_finished}','exam')->name('exam');

        Route::get('course-result/{seminar_id}/{seminar_type}','course_result')->name('course.result');
    });
});

// Certificate
// Route::group(['prefix'=> 'certificate', 'as' => 'certificate.', 'middleware' => ['auth']], function(){
//     Route::controller(SeminarCertificateController::class)->group(function () {
//         Route::get('pdf/Certificate', 'pdfCertificate')->name('certificate.pdf');
//     });
// });

app/Models/SeminarVideo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SeminarVideo extends Model
{
    use HasFactory;
    protected $primaryKey = 'id';

    protected $table = 'seminar_videos';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'm_seminar_id',
        'video_open_at',
        'video_close_at',
        'm3u8file_path',
        'keep_original_flag',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */

    public function getM3u8filePathAttribute($value){
        if (!empty($value)) {
            // $url = env('APP_SEMINAR_MANAGEMENT_URL').'video/'.$this->m_seminar_id.'/video.m3u8';
            $url = asset('video/'.$this->m_seminar_id.'/video.m3u8');
            return $url;
        }else{
            $url = null;
        }
    }

}

app/Http/Controllers/SeminarVideoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Symfony\Component\Process\Process;
use Illuminate\Support\Str;
use Validator;
use Carbon\Carbon;

use App\Models\SeminarVideo;
use App\Models\UserOnDemandHistory;
use App\Models\Seminar;
use App\Models\SeminarCertificate;

use PhpOffice\PhpWord;

class SeminarVideoController extends Controller
{   

    public function course_result($seminar_id,$seminar_type){

      $user = Auth::user();
      $user_id = $user->id;
      $certificate = SeminarCertificate::where(['user_id'=>$user_id, 'm_seminar_id'=>$seminar_id, 'seminar_type' => $seminar_type])->first();
      $seminar = Seminar::with('seminarGroup')->where('id',$seminar_id)->first();
      $data = [];
      $exam_status = "不合格";
      $with_certificate = false;
      $certificate_file = '';
      $output_file = '';
      if($certificate){
        $exam_status = ($certificate->correct_answer_count > 1) ? "合格" : "不合格";
        $with_certificate = ($certificate->correct_answer_count > 1) ? true : false;
        $certificate_file = $certificate->certificate_file;
        $output_file = '受講証明書_'. $seminar->category_name.'_'.$user->l_name.''.$user->f_name.'_';
      }
      if($seminar){

        // convert certificate
        exec('export HOME=/tmp && lowriter --convert-to pdf --outdir '.public_path().'/certificate_pdf '.public_path() .'/certificate_word/'.$certificate_file.'.docx');

        $data = ['seminar_id'=>$seminar_id, 'group_name' => $seminar->seminarGroup->group_name, 'exam_status' => $exam_status, 'with_certificate' => $with_certificate,'certificate_file' => $certificate_file.'.pdf', 'output_file' => $output_file];
        return view('SeminarVideo.course_result',compact('data','user'));
      }else{
        abort(404);
      }

    }

    public function index(){

      $user_id = Auth::user()->id;

      $today_date = Carbon::now();

      $seminarVideos = Seminar::selectRaw('m_seminars.id as seminar_id,seminar_videos.id as seminar_video_id, m_seminar_groups.group_name')
                            ->join('seminar_videos', 'seminar_videos.m_seminar_id', '=', 'm_seminars.id')
                            ->join('m_seminar_groups', 'm_seminar_groups.id', '=', 'm_seminars.m_seminar_group_id')
                            ->where('seminar_videos.video_open_at','<=',$today_date)->where('seminar_videos.video_close_at','>=',$today_date)
                            ->orderBy('m_seminar_id')->get();

      $videos_attend = UserOnDemandHistory::where('user_id',$user_id)->whereNotNull('attend_at')->get();

      if(!$seminarVideos->isEmpty()){
          $videos_attend->whereIn('m_seminar_group_id',$seminarVideos->pluck('id'));
      }

      $checker = [];

      if(!$videos_attend->isEmpty()){

          foreach ($seminarVideos->toArray() as $row) {

              $data['seminar_id'] =  $row['seminar_id'];
              $data['group_name'] =  $row['group_name'];
              if ($videos_attend->contains('m_seminar_id', $row['seminar_id'])){
                  $data['is_registered'] = true;
              }else{
                  $data['is_registered'] = false;
              }
              $checker[] = $data;
          }

      }

      if(Auth::user()->paid == 1){
        return view('SeminarVideo.index', compact('seminarVideos','checker'));
      }else{
        return view('Account.upload_participation_certificate');
      }
 
    }

    public function start_video($seminar_id){
      $user_id = Auth::user()->id;
      $with_certificate = SeminarCertificate::where(['user_id'=>$user_id, 'm_seminar_id'=>$seminar_id, 'seminar_type' => 'video'])->first();
      
      $seminar_detail = Seminar::selectRaw('m_seminar_groups.group_name,seminar_videos.video_times')
                        ->join('m_seminar_groups', 'm_seminar_groups.id', '=', 'm_seminars.m_seminar_group_id')
                        ->join('seminar_videos', 'seminar_videos.m_seminar_id', '=' , 'm_seminars.id')
                        ->find($seminar_id);
      // if($with_certificate){
      //   abort(404);
      // }else{
      //   if($seminar_detail){
      //     return view('SeminarVideo.start_video', compact('seminar_detail','seminar_id'));
      //   }else{
      //     abort(404);
      //   }
      // }
        return view('SeminarVideo.start_video', compact('seminar_detail','seminar_id'));


    }

    public function save_video($seminar_id){
      $user = Auth::user();
      $has_user_demand = UserOnDemandHistory::where('m_seminar_id', $seminar_id)->where('user_id', $user->id);

      if ($has_user_demand->count() > 0) {
          $user_demand_history = $has_user_demand->first();
          return redirect()->route('SeminarVideo.play.video', ['user_ondemand_history_id' => $user_demand_history->id]);
      }else{
        $data = new UserOnDemandHistory;
        $data->user_id = Auth::user()->id;
        $data->m_seminar_id = $seminar_id;
        $data->attend_at = Carbon::now();

        if($data->save()){
          return redirect()->route('SeminarVideo.play.video', ['user_ondemand_history_id' => $data->id]);
        }else{
          return Redirect::to(url()->previous());
        }
      }
    }

    public function play_video($user_ondemand_history_id){

        $user_id = Auth::user()->id;
        $user_ondemand_history = UserOnDemandHistory::find($user_ondemand_history_id);
        $is_exam = true;
        if($user_ondemand_history){
          $seminar_detail = Seminar::with(
            ["seminarGroup","video" ,"exams" => function($q){ 
              $q->inRandomOrder()->limit(3);
            }]
          )
          ->whereHas('seminarGroup')
          ->whereHas('video')
          ->whereHas('exams')
          ->find($user_ondemand_history->m_seminar_id);  

          if($seminar_detail){
            $with_certificate = SeminarCertificate::where(['user_id'=>$user_id, 'm_seminar_id'=>$user_ondemand_history->m_seminar_id, 'seminar_type' => 'video'])->first();
            if($with_certificate){
                $redirect = route('SeminarVideo.course.result', ['seminar_id' => $user_ondemand_history->m_seminar_id, 'seminar_type' => 'video']);                            
            }else{
                $redirect = route('SeminarVideo.exam', [$user_ondemand_history->id, 1]);
            }

              return view('SeminarVideo.play_video', compact('user_ondemand_history','seminar_detail', 'redirect'));

          }else{
            abort(404);
          }
        }
        abort(404);
    }

    public function exam($user_ondemand_history_id, $video_finished = 0){

        $user_id = Auth::user()->id;
        $user_ondemand_history = UserOnDemandHistory::find($user_ondemand_history_id);
        if($user_ondemand_history){
          $seminar_detail = Seminar::with(
            ["seminarGroup","video" ,"exams" => function($q){ 
              $q->whereNotNull('exam_question')->inRandomOrder()->limit(3);  
            }]
          )
          ->whereHas('seminarGroup')
          ->whereHas('video')
          ->whereHas('exams')
          ->find($user_ondemand_history->m_seminar_id);  

          $no_seminar_exam = false;

          if($seminar_detail->exams->isEmpty()){
            $no_seminar_exam = true;
            return view('SeminarVideo.exam', compact('user_ondemand_history','seminar_detail','no_seminar_exam'));
          }

          if($seminar_detail){
            $with_certificate = SeminarCertificate::where(['user_id'=>$user_id, 'm_seminar_id'=>$user_ondemand_history->m_seminar_id, 'seminar_type' => 'video'])->first();
            if($with_certificate){
              abort(404);
            }else{
              if($video_finished == 1){
                return view('SeminarVideo.exam', compact('user_ondemand_history','seminar_detail','no_seminar_exam'));
              }else{
                abort(404);
              }
            }
          }else{
            abort(404);
          }
        }
        abort(404);
    }



}

resources/views/SeminarVideo/course_result.blade.php
@extends('Layout.account.app')
@section('title', '受講者情報')

@section('css')
<style type="text/css">

</style>
@endsection

@section('content')
  <div class="row justify-content-center mt-2">
    <div class="col-sm-5 text-end">
       <a href="{{ route('account.index') }}" class="btn btn-outline-warning float-right">戻る</a>
    </div>
  </div>
	<div class="row justify-content-center mt-5">
		<div class="col-md-5 col-12">
            <div class="row">
				<!-- form label start -->
				<div class="col-sm-12">
					<label class="page-title">受講結果</label>
				</div>
			</div>

            <div class="row">
				<div class="col-sm-12 col-12">
					<div class="input-group mb-3">
					  <div class="input-group-prepend bg-primary input-label">
					    <span class="input-group-text bg-primary border-0" id="basic-addon1">氏名</span>
					  </div>
					  <input type="text" class="form-control bg-white" name="full_name" id="full_name" aria-describedby="basic-addon1" value="{{ $user->fullname }}" readonly>
                      <div class="invalid-feedback" id="err_full_name"></div>
                    </div>
				</div>

				<div class="col-sm-12 col-12">
					<div class="input-group mb-3">
					  <div class="input-group-prepend bg-primary input-label">
					    <span class="input-group-text bg-primary border-0" id="basic-addon2">会員番号</span>
					  </div>
					  <input type="text" class="form-control bg-white" name="membership_number" id="membership_number" aria-describedby="basic-addon2" value="{{ $user->certificate_id1 }} - {{ $user->certificate_id2 }}" readonly>
                      <div class="invalid-feedback" id="err_membership_number"></div>
                    </div>
				</div>
			</div>

			<div class="row mt-3">
				<div class="col-sm-12">
					<p><b>{{ $data['group_name'] }} &emsp;&emsp; {{ $data['exam_status'] }}</b></p>
				</div>
			</div>
			
			@if($data['with_certificate'] == true)
				<div class="row justify-content-end">
					<div class="col-md-12 text-right">
						<a type="button" class="btn btn-primary" href="{{url('/certificate_pdf/'.$data['certificate_file'])}}" download="{{ $data['output_file'] }}">証明書を取得する</a>
					</div>
				</div>
			@endif
	</div>
	</div>
@endsection

resources/views/SeminarVideo/exam.blade.php
@extends('Layout.account.app')
@section('title', '受講者情報')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('css/video.css') }}">
<style>
.div-options {
	 list-style-type:none;
	 margin-bottom: auto;
}

.div-options li {
    /*float:left;*/
    margin:0 5px 0 0;
    min-width:100%;
    /*height:40px;*/
    position:relative;
}

.div-options label.question-choice, .div-options input {
    display:block;
    position:inherit;
   /* top:0;
    left:0;
    right:0;
    bottom:0;*/
}

.div-options input[type="radio"] {
    opacity:0.011;
    z-index:100;
}

.div-options input[type="radio"]:checked + label.question-choice {
    background:#0004FD;
    color: white !important;
} 

.div-options label.question-choice {
 	padding:5px;
 	border:1px solid #0004FD; 
 	cursor:pointer;
    z-index:90;
    border-radius: 5px;
    text-align: center;
    /* padding: 12px; */
    font-weight: normal;
}

.div-options label.question-choice:hover {
     background:#0004FD;
     color: white;
}

.col-md-12.col-12.div-question.is-invalid {
    border: 1px solid #dc3545;
}

.invalid-feedback {
    margin-bottom: 0.25rem;
}

textarea {
  resize: none;
}

li.options-disabled {
    pointer-events: none;
}

</style>
@endsection


@section('content')
	<div class="row justify-content-center mt-5">
		<div class="col-md-5 col-12">
			@if($no_seminar_exam==false)

			<div id="exam_form_row" class="row">
				<!-- exam form-->
				<div class="col-md-12 col-12">

					<div class="card seminar-card border-primary">

					  <div class="card-body text-primary text-center">

						<div class="row mb-2">
							<div class="col-md-12 col-12 mt-2 text-center">
								<h5 class="error-div text-danger" style="display: none;"></h5>	
								{{-- <h5 class="answering-div">会場画面に表示されている問題に対する回答を答えてください.</h5> --}}
								<h5 class="review-div text-danger" style="display:none;">本当にこの回答でよろしいですね？.
									<span class="font-weight-bold">一度登録した回答は変更できません</span>
								</h5>
							</div>
						</div>
			
						<form id="exam_form">
							@csrf
							<input type="hidden" name="user_ondemand_history_id" value="{{ $user_ondemand_history->id }}">
							<div class="row">
			
									@if(!$seminar_detail->exams->isEmpty())	
										@foreach($seminar_detail->exams as $key => $eq)
											<input type="hidden" name="exam_id[]" value="{{$eq->id}}">
											<div class="col-md-12 col-12 div-question div-question-{{$eq->id}}">
												<div class="col-3">
													<p class="mb-0 float-left">問題 {{ $key+=1 }}</p>
												</div>
												<div class="col-12">
													<textarea class="form-control bg-white" rows="3" cols="3" readonly>{{$eq->exam_question}}</textarea>
												</div>
												<div class="col-md-5 col-sm-6 col-lg-5 float-right">
													<ul class="div-options">
														<div class="row" style="max-height:100px;">
															<div class="col">
																<li>
																	<input type="radio" class="form-control" id="1-{{$eq->id}}" value="1" name="q-{{ $eq->id }}" />
																	<label class="question-choice" for="1-{{$eq->id}}">はい</label>
																</li>
															</div>	
															<div class="col">
																<li>
																	<input type="radio" class="form-control" id="2-{{$eq->id}}" value="0" name="q-{{ $eq->id }}" />
																	<label class="question-choice" for="2-{{$eq->id}}">いいえ</label>
																</li>
															</div>	
														</div>
														<div class="invalid-feedback" id="err_{{ $eq->id }}"></div>
													</ul>
												</div>
											</div>
										@endforeach
									@endif
			
									<div class="col-md-12 text-center mt-2 p-2">
										<button type="button" data-type="review" class="btn btn-outline-primary btn-save review-btn">確認する</button>
										<button type="button" data-type="register" class="btn btn-outline-primary btn-save register-btn" style="display:none;">回答を登録する</button>
									</div>	
									
							</div>
			
						</form>
			
					   	
					  </div>

					</div>

				</div>
			</div>

			@else

			
			  
			<div class="col-sm-12 text-center">
				<h5 class="text-danger text-center mb-5">ゼミ試験が見つかりません。</h5>
				<a href="{{route('account.index')}}" class="btn btn-primary">HOMEへ戻る</a>
			</div>

			@endif
			
		</div>
	</div>
@endsection


@section('script')

<script type="text/javascript">
	var review = false;
	$(".btn-save").on('click', function(e){
		 e.preventDefault(e);
		var type = $(this).data('type');
	    
		$('.error-div').hide();

		if(type == 'review'){
			
			if(review==false){ //show are you sure etc.
				$('.review-div').show();
				$('.register-btn').show();
				$('.review-btn').text('変更する');
				$('.answering-div').hide();
				//disable fields here
				$("#exam_form input[type=radio]").attr('disabled', true);
				$("#exam_form input[type=radio]").parent().addClass("options-disabled");
				review = true;
			}else{ //hide
				$('.review-btn').text('確認する');
				$('.review-div').hide();
				$('.register-btn').hide();
				$('.answering-div').show();
				//enable fields here
				$("#exam_form input[type=radio]").attr('disabled', false);
				$("#exam_form input[type=radio]").parent().removeClass("options-disabled");
				review = false;
			}

			return false;
		}

		$("#exam_form input[type=radio]").attr('disabled', false); //re enable radio before submit
		const data = $('#exam_form').serialize();
	    $.ajax({
		    	type:"POST",
		        url: "{{ route('seminar_exam.user_on_demand_exam.store') }}",
		        data:data,
		        cache:false,
		        beforeSend:function(){
		           	$(".register-btn").prop('disabled', true);
		        },
		    	success:function(response){
		        
		        $(".register-btn").prop('disabled', false);
		     	
		     	review = false;

		        if(response.status == true){
		           	window.location = response.redirect;
		        }else{

		        	if(response.type=='answer_all'){
		        		$('.review-div').hide();
						$('.register-btn').hide();
					
		        		$('.error-div').text('全ての問題を解答してください');
	        	 		$('.error-div').show();
		        	}else if(response.type=='answered'){
		        		//window.location = response.redirect;
		        	}
		        }		        
		    },
		    error:function(error){
		        console.log(error);
		        $(".register-btn").prop('disabled', false);
		    }
		});
	});

	//use this to trigger exam show
	// $('#exam_form_row').show();
	
</script>

@endsection

resources/views/SeminarVideo/index.blade.php
@extends('Layout.account.app')
@section('title', '受講者情報')

@section('css')
<style type="text/css">

</style>
@endsection


@section('content')
	
	<div class="row justify-content-center mt-2">
		<div class="col-sm-5 text-end">
		   <a href="{{ route('account.index') }}" class="btn btn-outline-warning float-right">戻る</a>
		</div>
	</div>
	<div class="row justify-content-center mt-5">
		<div class="col-md-5 col-12">

            <div class="row">
				<!-- form label start -->
				<div class="col-sm-12">
					<label class="page-title">動画受講講座一覧</label>
				</div>
			</div>

            <div class="row">
				<!-- form label start -->
				<div class="col-sm-12 text-center">
					<label class="page-row-title">動画による受講可能な講座</label>
				</div>

				@if(!$seminarVideos->isEmpty() && empty($checker))
					@foreach($seminarVideos as $row)
					 	<div class="col-md-12 text-center mb-2">
	                        <a  href="{{ route('SeminarVideo.start', ['seminar_id' => $row->seminar_id] ) }}" class="btn btn-outline-primary btn-block">{{ $row->group_name }}</a>
	                    </div>
	                @endforeach
	            @endif

	            @if(!empty($checker))
					@foreach($checker as $row)
						@if($row['is_registered'] == false)
							<div class="col-md-12 text-center mb-2">
		                        <a  href="{{ route('SeminarVideo.start', ['seminar_id' => $row['seminar_id']] ) }}" class="btn btn-outline-primary btn-block">{{ $row['group_name'] }}</a>
		                    </div>
						@endif
					@endforeach
				@endif	

	            <!-- Course Taken -->
	            <div class="col-sm-12 text-center">
					<label class="page-row-title">受講済の講座</label>
				</div>

				@if(!empty($checker))
					@foreach($checker as $row)
						@if($row['is_registered'] == true)
							{{--
								@if(check_seminar_certificate($row['seminar_id']))
									<div class="col-md-12 text-center mb-2">
				                        <a  href="{{ route('SeminarVideo.course.result', ['seminar_id' => $row['seminar_id'], 'seminar_type' => 'video'] ) }}" class="btn btn-outline-primary btn-block">{{ $row['group_name'] }}</a>
				                    </div>
								@else
								@endif
								--}}

							<div class="col-md-12 text-center mb-2">
		                        <a  href="{{ route('SeminarVideo.start', ['seminar_id' => $row['seminar_id']] ) }}" class="btn btn-outline-primary btn-block">{{ $row['group_name'] }}</a>
		                    </div>
						@endif
					@endforeach
				
				@endif

			</div>
		</div>
	</div>
@endsection

resources/views/SeminarVideo/start_video.blade.php
@extends('Layout.account.app')
@section('title', '受講者情報')

@section('css')
<style type="text/css">

</style>
@endsection


@section('content')
	<div class="row justify-content-center mt-5">
		<div class="col-md-5 col-12">
            <div class="row">
				<!-- form label start -->
				<div class="col-sm-12">
					<label class="page-title">{{ $seminar_detail->group_name }}</label>
				</div>
                
			</div>

            <div class="row">
				<!-- form label start -->
				<div class="col-sm-8">
					<p class="mt-1">動画による受講を開始しますか</p>
				</div>

				<div class="col-sm-4">
					<label class="text-danger">講義時間</label> &emsp;&nbsp; <label>{{ $seminar_detail->video_times }} 分</label>
					<a href="{{ route('SeminarVideo.save.video', ['seminar_id' => $seminar_id] ) }}" class="btn btn-primary btn-block">受講する</a>
				</div>
			</div>

			<div class="row mt-3">
				<div class="col-sm-12">
					<p>動画閲覧後、問題が出題されます。回答をお忘れないようにお願いします。</p>
					<p class="text-danger">途中でブラウザの再読み込み、ブラウザを閉じる等を行うと、最初から受講し直しとなります</p>
				</div>
			</div>
			<div class="row justify-content-center mt-2">
				<div class="col-sm-12 text-end">
					<a href="{{ route('account.index') }}" class="btn btn-outline-warning float-right">戻る</a>
				</div>
			</div>

		</div>
	</div>
@endsection