routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SeminarController;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\SeminarVideoController;
use App\Http\Controllers\SeminarCertificateController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('Auth.index');
})->name('login');

Route::get('/', function () {
    return view('Auth.register');
})->name('registration');

Route::controller(UserController::class)->group(function () {
	Route::get('registration-verify/{token}','showVerifyEmail')->name('registration_verify.get');
	Route::post('registration','store')->name('registration.store');
    Route::get('registration-success', 'success')->name('registration.success');
});

//Authentications/Login
Route::group(['prefix'=> 'auth'], function(){
	Route::name('auth.')->group(function () {
		// For Login
		Route::controller(AuthController::class)->group(function () {
	 		 Route::post('request', 'authenticate')->name('authenticate');
	 		 Route::get('test', 'test')->name('test');
		});

		// For Forgot Password
		Route::controller(ForgotPasswordController::class)->group(function () {
			Route::get('forget-password', 'index')->name('forget.password.get');
			Route::post('forget-password','store')->name('forget.password.post');
			Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
			Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
			Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
			Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
		});
	});
});


// Route::get('account/', 'AccountController@index')->name('account.index');

Route::group(['prefix'=> 'account', 'middleware' => ['auth']], function(){
    Route::name('account.')->group(function () {
        // Main Manager Page
        Route::controller(AccountController::class)->group(function () {
            Route::get('','index')->name('index');
            Route::get('show/{id?}','showUserAccount')->name('show');
            Route::get('edit/{id?}','editUserAccount')->name('edit');
            Route::post('update/{id?}','update')->name('update');

            Route::post('account/certificate/','uploadCertificate')->name('upload.certificate');
        });
    });


    Route::name('qrcode.')->group(function () {
        // QRcode
        Route::controller(QrCodeController::class)->group(function () {
            Route::get('qrcode-details/{id}/{seminar_id}','index')->name('index');
            Route::get('check-reception/{id}','checkSeminar')->name('check.seminar');
            Route::get('error-reception/{id}','errorSeminar')->name('error.seminar');
            Route::get('in-reception/{id}','inSeminar')->name('in.seminar');
            Route::get('out-reception/{id}','outSeminar')->name('out.seminar');
        });
    });

    Route::name('seminar.')->group(function () {
        // Seminar Pages
        Route::controller(SeminarController::class)->group(function () {
            Route::get('seminar-list/{seminar_group_id}','index')->name('index'); //this would be seminar list
            Route::get('seminar-detail/{id}','show')->name('show');  //this would be seminar detail
            Route::post('seminar-register','register')->name('register');  //this would be seminar registration
            Route::post('seminar-cancel','cancel')->name('cancel');  //this would be cancel of seminar registration
            Route::get('seminar-register-action', 'register_action')->name('register.action');

            Route::get('seminar-user-detail/{id}','user_detail')->name('user.detail');  //this would be user seminar detail

        });
    });

    Route::name('seminar_exam.')->group(function () {
        // Seminar Exam
        Route::controller(ExamController::class)->group(function () {
            Route::get('seminar-exam/{seminar_registration_id}','index')->name('index');
            Route::post('seminar-exam-store/','store')->name('store');
            Route::get('seminar-exam-success/{seminar_registration_id}','success')->name('success');
            Route::post('seminar-on-demand-exam-store/','userOnDemandExamstore')->name('user_on_demand_exam.store');
        });
    });


    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

});

// video on demand
Route::group(['prefix'=> 'seminar-video', 'as' => 'SeminarVideo.', 'middleware' => ['auth']], function(){
    Route::controller(SeminarVideoController::class)->group(function () {
        Route::get('','index')->name('index');
        Route::get('start-video/{seminar_id}','start_video')->name('start');
        Route::get('save-video/{seminar_id}','save_video')->name('save.video');
        Route::get('play-video/{user_ondemand_history_id}','play_video')->name('play.video');
        Route::get('exam/{user_ondemand_history_id}/{video_finished}','exam')->name('exam');

        Route::get('course-result/{seminar_id}/{seminar_type}','course_result')->name('course.result');
    });
});

// Certificate
// Route::group(['prefix'=> 'certificate', 'as' => 'certificate.', 'middleware' => ['auth']], function(){
//     Route::controller(SeminarCertificateController::class)->group(function () {
//         Route::get('pdf/Certificate', 'pdfCertificate')->name('certificate.pdf');
//     });
// });

app/Http/Controllers/QrCodeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SeminarRegistration;
use App\Models\UserSeminarStatus;
use Carbon\Carbon;
use App\Models\User;
use Illuminate\Support\Str;
use DB;
use Mail;
use Hash;
use Auth;

class QrCodeController extends Controller
{
    public function index($id, $seminar_id)
    {
       $user = Auth::user();
       $today = now();
        $has_seminar = SeminarRegistration::whereHas('seminar', function($seminars) use($today){
        $seminars->whereDate('reception_open_at', '<=', $today->format('Y-m-d'))->whereTime('reception_open_at', '<=', $today->toTimeString());
       })->where('id', $id)->where('user_id', $user->id)->whereNull('canceled_at');

       if ($has_seminar->count() > 0) {
       	$seminar = $has_seminar->first();
        return view('QrCode.index', compact('seminar'));
       }else{
       	return redirect(route('seminar.user.detail', ['id' => $id]));
       }
    }

    public function checkSeminar($id){
      $has_reception = UserSeminarStatus::where('seminar_registration_id', $id);
      if ($has_reception->count() > 0) {
        $reception = $has_reception->first();
        $data = [];

        if (!empty($reception->reception_in_err) || !empty($reception->reception_out_err)) {
          return response()->json(['status' => true, 'redirect' => route('qrcode.error.seminar', [$id])]);
        }else{
          if (!empty($reception->reception_in_at) && !empty($reception->reception_out_at) && !empty($reception->exam_answered_at)) {
            return response()->json(['status' => true, 'redirect' => route('qrcode.out.seminar', [$id])]);
          }elseif (!empty($reception->reception_in_at) && empty($reception->exam_answered_at)) {
            return response()->json(['status' => true, 'redirect' => route('qrcode.in.seminar', [$id])]);
          }
        }
      }else{
      return response()->json(['status' => false, 'message' => 'Stay Here..']);
      }
    }


    public function errorSeminar($id){
       $user = Auth::user();
       $seminar = SeminarRegistration::with(['seminar'])->where('id', $id)->where('user_id', $user->id)->first();
       return view('QrCode.err_status', compact('seminar'));
    }

    public function inSeminar($id){
       $user = Auth::user();
      $seminar = SeminarRegistration::with(['seminar'])->where('id', $id)->where('user_id', $user->id)->first();
      return view('QrCode.in_status', compact('seminar'));
    }

    public function outSeminar($id){
       $user = Auth::user();
      $seminar = SeminarRegistration::with(['seminar'])->where('id', $id)->where('user_id', $user->id)->first();
      return view('QrCode.out_status', compact('seminar'));
    }

}

resources/views/QrCode/err_status.blade.php
@extends('Layout.qrcode.app')
@section('title', '今後の講座 予定')
@section('css')
@endsection

@php $user = Auth::user(); @endphp

@section('content')
	<div class="row justify-content-center" style="margin-top: 165px;">
		<div class="col-md-5 col-12">
            <div class="card">
				<div class="card-body text-primary">
					<div class="row">
						<div class="col-md-4 col-4">
							<i class="fa fa-user fa-3x"></i>
						</div>
						<div class="col-md-8 col-8 mt-2">
							<h3><b>{{ $user->l_name }} {{ $user->f_name }}</b></h3>
						</div>
						<div class="col-md-12 col-12 mt-5">
							<p class="m-1"><b>セミナー番号 {{ $seminar->seminar->category_no }}</b></p>
							<p class="m-1"><b>領域 {{ $seminar->seminar->category_name }} {{ $seminar->seminar->seminar_title }}</b></p>

							<div class="text-center mt-3 mb-5">
									<i class="fa fa-exclamation text-danger fa-5x"></i>
							</div>
							<p class="m-1 text-center">読み取り時にエラーが発生しました</p>
							<p class="m-1 text-center">会場スタッフにご連絡をお願いします</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/QrCode/in_status.blade.php
@extends('Layout.qrcode.app')
@section('title', '今後の講座 予定')
@section('css')
@endsection

@php $user = Auth::user(); @endphp

@section('content')
	<div class="row justify-content-center" style="margin-top: 165px;">
		<div class="col-md-5 col-12">
            <div class="card">
				<div class="card-body text-primary">
					<div class="row">
						<div class="col-md-4 col-4">
							<i class="fa fa-user fa-3x"></i>
						</div>
						<div class="col-md-8 col-8 mt-2">
							<h3><b>{{ $user->l_name }} {{ $user->f_name }}</b></h3>
						</div>
						<div class="col-md-12 col-12 mt-5">
							<p class="m-1"><b>セミナー番号 {{ $seminar->seminar->category_no }}</b></p>
							<p class="m-1"><b>領域 {{ $seminar->seminar->category_name }} {{ $seminar->seminar->seminar_title }}</b></p>

							<div class="text-center mt-3 mb-5">
								<i class="fa fa-check text-primary fa-5x"></i>
							</div>
							<p class="m-1 text-center">参加受付が完了しました</p>
						</div>
						<div class="col-md-12 col-12  text-center">
							<a href="{{ route('seminar.user.detail', [$seminar->id]) }}" class="btn btn-outline-primary px-5">講義詳細へ戻る</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/QrCode/index.blade.php
@extends('Layout.qrcode.app')
@section('title', '今後の講座 予定')
@section('css')
@endsection

@php $user = Auth::user(); @endphp

@section('content')
	<div class="row justify-content-center" style="margin-top: 165px;">
		<div class="col-md-5 col-12">
            <div class="card">
				<div class="card-body text-primary">
					<div class="row">
						<div class="col-md-4 col-4">
							<i class="fa fa-user fa-3x"></i>
						</div>
						<div class="col-md-8 col-8 mt-2">
							<h3><b>{{ $user->l_name }} {{ $user->f_name }}</b></h3>
						</div>
						<div class="col-md-12 col-12 mt-5">
							<p class="m-1"><b>セミナー番号 {{ $seminar->seminar->category_no }} 領域 {{ $seminar->seminar->category_no }}</b></p>
							<p class="m-1"><b>{{ $seminar->seminar->category_name }} / {{ $seminar->seminar->seminar_title }}</b></p>

							<div class="text-center mt-3 mb-5">
								<center><div id="qrcode"></div></center>
								<h1>{{ $seminar->qr_code }}</h1>
							</div>

							<p class="m-1"><b>会場に設置されているQRコードリーダーに表示されているQRコードを読み込ませてください。</b></p>
							<p class="m-1"><b>読み込み処理後、１分経過しても表示画面が変わらない場合は、会場スタッフまでご連絡ください。</b></p>
						</div>
                        <div class="col-sm-12 text-center mt-3">
                            <a href="{{route('seminar.user.detail',$seminar->id)}}" class="btn btn-primary">戻る</a>
                         </div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('script')
<script type="text/javascript" src="{{ asset('js/qrcode.min.js') }}"></script>

<script type="text/javascript">
	$(document).ready(function(){
		var qrcode = new QRCode("qrcode", {
		    text: "{{ $seminar->qr_code }}",
		    width: 180,
		    height: 180,
		    colorDark : "#0004FD",
		    colorLight : "#ffffff",
		    correctLevel : QRCode.CorrectLevel.H
		});
	});

	function check_qr_reception(){
		$.ajax({
		    type:"GET",
		    url:"{{ route('qrcode.check.seminar', [$seminar->id]) }}",
		    data:{},
		    dataType:'json',
		    beforeSend:function(){
		    },
		    success:function(response){
		      // console.log(response);
		      if (response.status) {
			      window.location = response.redirect;
		      }
		    },
		    error: function(error){
		      console.log(error);
		    }
		  });
	}

	setInterval(function(){
		check_qr_reception();
	}, 3000);
</script>
@endsection

resources/views/QrCode/out_status.blade.php
@extends('Layout.qrcode.app')
@section('title', '今後の講座 予定')
@section('css')
@endsection

@php $user = Auth::user(); @endphp

@section('content')
	<div class="row justify-content-center" style="margin-top: 165px;">
		<div class="col-md-5 col-12">
            <div class="card">
				<div class="card-body text-primary">
					<div class="row">
						<div class="col-md-4 col-4">
							<i class="fa fa-user fa-3x"></i>
						</div>
						<div class="col-md-8 col-8 mt-2">
							<h3><b>{{ $user->l_name }} {{ $user->f_name }}</b></h3>
						</div>
						<div class="col-md-12 col-12 mt-5">
							<p class="m-1"><b>セミナー番号 {{ $seminar->seminar->category_no }}</b></p>
							<p class="m-1"><b>領域 {{ $seminar->seminar->category_name }} {{ $seminar->seminar->seminar_title }}</b></p>

							<div class="text-center mt-3 mb-5">
								<i class="fa fa-check text-primary fa-5x"></i>
							</div>
							<p class="m-1 text-center">退席確認が完了しました</p>
						</div>
						<div class="col-md-12 col-12 text-center">
							<a href="{{ route('account.index') }}" class="btn btn-outline-primary px-5">講義詳細へ戻る</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection