routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SeminarController;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\SeminarVideoController;
use App\Http\Controllers\SeminarCertificateController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('Auth.index');
})->name('login');

Route::get('/', function () {
    return view('Auth.register');
})->name('registration');

Route::controller(UserController::class)->group(function () {
	Route::get('registration-verify/{token}','showVerifyEmail')->name('registration_verify.get');
	Route::post('registration','store')->name('registration.store');
    Route::get('registration-success', 'success')->name('registration.success');
});

//Authentications/Login
Route::group(['prefix'=> 'auth'], function(){
	Route::name('auth.')->group(function () {
		// For Login
		Route::controller(AuthController::class)->group(function () {
	 		 Route::post('request', 'authenticate')->name('authenticate');
	 		 Route::get('test', 'test')->name('test');
		});

		// For Forgot Password
		Route::controller(ForgotPasswordController::class)->group(function () {
			Route::get('forget-password', 'index')->name('forget.password.get');
			Route::post('forget-password','store')->name('forget.password.post');
			Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
			Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
			Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
			Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
		});
	});
});


// Route::get('account/', 'AccountController@index')->name('account.index');

Route::group(['prefix'=> 'account', 'middleware' => ['auth']], function(){
    Route::name('account.')->group(function () {
        // Main Manager Page
        Route::controller(AccountController::class)->group(function () {
            Route::get('','index')->name('index');
            Route::get('show/{id?}','showUserAccount')->name('show');
            Route::get('edit/{id?}','editUserAccount')->name('edit');
            Route::post('update/{id?}','update')->name('update');

            Route::post('account/certificate/','uploadCertificate')->name('upload.certificate');
        });
    });


    Route::name('qrcode.')->group(function () {
        // QRcode
        Route::controller(QrCodeController::class)->group(function () {
            Route::get('qrcode-details/{id}/{seminar_id}','index')->name('index');
            Route::get('check-reception/{id}','checkSeminar')->name('check.seminar');
            Route::get('error-reception/{id}','errorSeminar')->name('error.seminar');
            Route::get('in-reception/{id}','inSeminar')->name('in.seminar');
            Route::get('out-reception/{id}','outSeminar')->name('out.seminar');
        });
    });

    Route::name('seminar.')->group(function () {
        // Seminar Pages
        Route::controller(SeminarController::class)->group(function () {
            Route::get('seminar-list/{seminar_group_id}','index')->name('index'); //this would be seminar list
            Route::get('seminar-detail/{id}','show')->name('show');  //this would be seminar detail
            Route::post('seminar-register','register')->name('register');  //this would be seminar registration
            Route::post('seminar-cancel','cancel')->name('cancel');  //this would be cancel of seminar registration
            Route::get('seminar-register-action', 'register_action')->name('register.action');

            Route::get('seminar-user-detail/{id}','user_detail')->name('user.detail');  //this would be user seminar detail

        });
    });

    Route::name('seminar_exam.')->group(function () {
        // Seminar Exam
        Route::controller(ExamController::class)->group(function () {
            Route::get('seminar-exam/{seminar_registration_id}','index')->name('index');
            Route::post('seminar-exam-store/','store')->name('store');
            Route::get('seminar-exam-success/{seminar_registration_id}','success')->name('success');
            Route::post('seminar-on-demand-exam-store/','userOnDemandExamstore')->name('user_on_demand_exam.store');
        });
    });


    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

});

// video on demand
Route::group(['prefix'=> 'seminar-video', 'as' => 'SeminarVideo.', 'middleware' => ['auth']], function(){
    Route::controller(SeminarVideoController::class)->group(function () {
        Route::get('','index')->name('index');
        Route::get('start-video/{seminar_id}','start_video')->name('start');
        Route::get('save-video/{seminar_id}','save_video')->name('save.video');
        Route::get('play-video/{user_ondemand_history_id}','play_video')->name('play.video');
        Route::get('exam/{user_ondemand_history_id}/{video_finished}','exam')->name('exam');

        Route::get('course-result/{seminar_id}/{seminar_type}','course_result')->name('course.result');
    });
});

// Certificate
// Route::group(['prefix'=> 'certificate', 'as' => 'certificate.', 'middleware' => ['auth']], function(){
//     Route::controller(SeminarCertificateController::class)->group(function () {
//         Route::get('pdf/Certificate', 'pdfCertificate')->name('certificate.pdf');
//     });
// });

app/Models/Exam.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Exam extends Model
{
    use HasFactory;

    protected $primaryKey = 'id';
    
    protected $table = 'exams';

    protected $fillable = [
        'm_seminar_id',
        'question_no',
        'exam_question',
        'answer',
    ];

    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];
    
    
}

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\Process\Process;
use Illuminate\Support\Str;
use Validator;
use Carbon\Carbon;



use App\Models\User;
use App\Models\Seminar;
use App\Models\SeminarGroup;
use App\Models\SeminarRegistration;
use App\Models\UserExam;
use App\Models\UserSeminarStatus;
use App\Models\UserOnDemandHistory;
use App\Models\SeminarCertificate;

use PDF;
use PhpOffice\PhpWord;

class ExamController extends Controller
{

    public function index($seminar_registration_id){

        $user = Auth::user();

        if($seminar_registration_id){

            $seminar_registration = SeminarRegistration::where('id',$seminar_registration_id)->where('user_id',$user->id)->whereNull('canceled_at')->first();

            if($seminar_registration){
                $seminar = Seminar::has('exams')->with(["exams" => function($q){ 
                    $q->where('seminar_use',1)->orderBy('question_no');
                }])->find($seminar_registration->m_seminar_id);
               
                if($seminar){
                    $exam_ids = $seminar->exams->pluck('id');

                    //check if user has already answered the exam.
                    $user_exams = UserExam::whereIn('exam_id',$exam_ids)->where('seminar_registration_id',$seminar_registration->id)->where('user_id',$user->id)->get();

                    if(!$user_exams->isEmpty()){
                        return redirect()->route('seminar.user.detail', ['id' => $seminar_registration->id]);
                    }

                    $user_seminar_status = UserSeminarStatus::where('seminar_registration_id',$seminar_registration->id)->first();

                    if(!$user_seminar_status){
                        return redirect()->route('seminar.user.detail', ['id' => $seminar_registration->id]);
                    }

                    return view('Exam.index',compact('seminar_registration','seminar','user'));
                }else{ //seminar has no exams or seminar doesn't exists
                    return redirect()->route('seminar.user.detail', ['id' => $seminar_registration->id]); 
                }
               
            }else{ //seminar has no exams or seminar doesn't exists
                    return redirect()->route('seminar.user.detail', ['id' => $seminar_registration_id]); 
                }
            
          
        }

    }

    public function store(Request $request){

        $user = Auth::user();

        $rules=[];

        //validate/get the user registration and seminar exams first
        if($request->filled('seminar_registration_id')){
            $seminar_registration = SeminarRegistration::where('id',$request->seminar_registration_id)->where('user_id',$user->id)->whereNull('canceled_at')->first();
            if($seminar_registration){

                //validate user_seminar_status
                $user_seminar_status = UserSeminarStatus::where('seminar_registration_id',$request->seminar_registration_id)->first();

                if(!$user_seminar_status){
                    return redirect()->route('seminar.user.detail', ['id' => $seminar_registration->id]);
                }

                if($user_seminar_status && $user_seminar_status->exam_answered_at!=null){
                    return response()->json([
                        'status' => false, 
                        'type' => 'answered',
                        'message' => 'fail', 
                        'redirect' => route('seminar.user.detail', ['id' => $seminar_registration->id])
                    ]);
                }

                $seminar = Seminar::has('exams')->with(["exams" => function($q){ 
                    $q->where('seminar_use',1)->orderBy('question_no');
                    }])->find($seminar_registration->m_seminar_id);
                if($seminar){
                  
                    foreach($seminar->exams as $key => $eq){
                        $rules["q-".$eq->id] = 'required';
                    }

                    $validator = \Validator::make($request->all(),$rules,[]);

                    if ($validator->fails()) {
                        return response()->json(['status' => false, 'type' => 'answer_all','error' => $validator->errors()]);
                    }
                    
                    //build insert data
                    $data = array();
                    foreach($seminar->exams as $key => $eq){

                        $field['user_id'] = $user->id;
                        $field['seminar_registration_id'] = $seminar_registration->id;
                        $field['exam_id'] = $eq->id;
                        $field['answer'] = $request->input('q-'.$eq->id);
                        $field['correct'] = ($eq->answer == $request->input('q-'.$eq->id) ? 1 : 0);
                        $field['created_at'] = now();
                        $data[] = $field;

                    }
                    //insert records
                    UserExam::insert($data);

                    $user_exam_query = UserExam::
                    where('seminar_registration_id',$seminar_registration->id);
                    
                    $user_exams = $user_exam_query->get();
                    if(!$user_exams->isEmpty()){

                        $user_exams_correct = $user_exam_query->where('correct',1)->count();
                
                        //SeminarCertificate
                        if($user_exams_correct > 1){

                            //generate certificate pdf
                            $file_name = 'JBA'.$seminar->m_seminar_group_id.'_'.$user->id.'_seminar';
                            $full_name = $user->l_name . " " . $user->f_name;
                            $this->convertWordToPDF($full_name,$seminar->format_url,$file_name);

                            $sem_cert_arry = [
                                'm_seminar_group_id' => $seminar->m_seminar_group_id,
                                'm_seminar_id' => $seminar_registration->m_seminar_id,
                                'user_id' => $user->id,
                                'user_exam_id1' => '',
                                'user_exam_id2' => '',
                                'user_exam_id3' => '',
                                'correct_answer_count' => $user_exams_correct,
                                'certificate_file' => $file_name,
                                'seminar_type' => 'seminar',
                                'exam_at' => now(),
                            ];

                            foreach($user_exams as $key => $exam){
                                $sem_cert_arry['user_exam_id'.$key+1] = $exam->id;
                            }

                            $seminar_certificate = SeminarCertificate::create($sem_cert_arry);
                        }

                    }

                    UserSeminarStatus::where('seminar_registration_id',$seminar_registration->id)->update(['exam_answered_at' => now()]);
                    return response()->json([
                        'status' => true, 
                        'message' => 'success', 
                        'redirect' => route('seminar_exam.success', ['seminar_registration_id' => $seminar_registration->id])
                    ]);

                }
            }
        }

    }

    public function userOnDemandExamstore(Request $request){

        $user = Auth::user();

        $rules=[];

        if($request->filled('user_ondemand_history_id')){
            $user_ondemand_history = UserOnDemandHistory::where('id',$request->user_ondemand_history_id)->where('user_id',$user->id)->first();
            if($user_ondemand_history){
  
                $seminar = Seminar::has('exams')->with(["exams" => function($q) use($request){ 
                        $q->whereIn('id',$request->exam_id)->orderBy('question_no');
                    }])->find($user_ondemand_history->m_seminar_id);
                if($seminar){
                  
                    foreach($seminar->exams as $key => $eq){
                        $rules["q-".$eq->id] = 'required';
                    }

                    $validator = \Validator::make($request->all(),$rules,[]);

                    if ($validator->fails()) {
                        return response()->json(['status' => false, 'type' => 'answer_all','error' => $validator->errors()]);
                    }
                    
                    //build insert data
                    $data = array();
                    foreach($seminar->exams as $key => $eq){

                        $field['user_id'] = $user->id;
                        $field['m_seminar_id'] = $user_ondemand_history->m_seminar_id;
                        $field['user_ondemand_history_id'] = $user_ondemand_history->id;
                        $field['exam_id'] = $eq->id;
                        $field['answer'] = $request->input('q-'.$eq->id);
                        $field['correct'] = ($eq->answer == $request->input('q-'.$eq->id) ? 1 : 0);
                        $field['created_at'] = now();
                        $data[] = $field;

                    }
                    
                    DB::beginTransaction();

                    // insert exam records
                    UserExam::insert($data);

                    $user_exam_query = UserExam::
                    where('user_ondemand_history_id',$user_ondemand_history->id)
                    ->where('m_seminar_id',$user_ondemand_history->m_seminar_id);
                    
                    $user_exams = $user_exam_query->get();
                    if(!$user_exams->isEmpty()){

                        $user_exams_correct = $user_exam_query->where('correct',1)->count();
                
                        //SeminarCertificate
                        if($user_exams_correct > 1){

resources/views/Exam/index.blade.php
@extends('Layout.qrcode.app')
@section('title', '今後の講座 予定')
@section('css')

<style>
	
.div-options {
	 list-style-type:none;
	 margin-bottom: auto;
}

.div-options li {
    /*float:left;*/
    margin:0 5px 0 0;
    min-width:100%;
    /*height:40px;*/
    position:relative;
}

.div-options label.question-choice, .div-options input {
    display:block;
    position:inherit;
   /* top:0;
    left:0;
    right:0;
    bottom:0;*/
}

.div-options input[type="radio"] {
    opacity:0.011;
    z-index:100;
}

.div-options input[type="radio"]:checked + label.question-choice {
    background:#0004FD;
    color: white !important;
} 

.div-options label.question-choice {
 	padding:5px;
 	border:1px solid #0004FD; 
 	cursor:pointer;
    z-index:90;
    border-radius: 5px;
    text-align: center;
    padding: 12px;
    font-weight: normal;
}

.div-options label.question-choice:hover {
     background:#0004FD;
     color: white;
}

.col-md-12.col-12.div-question.is-invalid {
    border: 1px solid #dc3545;
}

.invalid-feedback {
    margin-bottom: 0.25rem;
}

li.options-disabled {
    pointer-events: none;
}


</style>
@endsection

@section('content')
	<div class="row justify-content-center" style="margin-top: 165px;">
		<div class="col-md-5 col-12">
            <div class="card">
				<div class="card-body text-primary">
					<div class="row pr-4 pl-4">
						<div class="col-md-4 col-4">
							<i class="fa fa-user fa-3x"></i>
						</div>
						<div class="col-md-8 col-8 mt-2">
							<h4 class="font-weight-bold">{{ $user->l_name }} {{ $user->f_name }}</h4>
						</div>
						<div class="col-md-12 col-12 mt-2">
							<p>セミナー番号{{ $seminar->category_no }} 総論 {{ $seminar->category_no }} ({{ $seminar->category_name }})</p>
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-md-12 col-12 mt-2 text-center">
							<h5 class="error-div text-danger" style="display: none;"></h5>	
							<h5 class="answering-div">会場画面に表示されている問題に対する回答を答えてください.</h5>
							<h5 class="review-div text-danger" style="display:none;">本当にこの回答でよろしいですね？.
								<span class="font-weight-bold">一度登録した回答は変更できません</span>
							</h5>
						</div>
					</div>

					<form id="exam_form">
						@csrf
						<input type="hidden" name="seminar_registration_id" value="{{ $seminar_registration->id }}">
						<div class="row">

								@if(!$seminar->exams->isEmpty())	
									@foreach($seminar->exams as $key => $eq)
										<div class="col-md-12 col-12 div-question div-question-{{$eq->id}}">
											
											<label class="mb-0">問題 {{ $key+=1 }}</label>
											<ul class="div-options">
												<div class="row">
													
													<div class="col">
														<li>
														    <input type="radio" class="form-control" id="1-{{$eq->id}}" value="1" name="q-{{ $eq->id }}" />
														    <label class="question-choice" for="1-{{$eq->id}}">はい</label>
														</li>
													</div>	
													<div class="col">
														<li>
													    	<input type="radio" class="form-control" id="2-{{$eq->id}}" value="0" name="q-{{ $eq->id }}" />
														    <label class="question-choice" for="2-{{$eq->id}}">いいえ</label>
														</li>
													</div>	
												</div>
												<div class="invalid-feedback" id="err_{{ $eq->id }}"></div>
											</ul>


										</div>
									@endforeach
								@endif

								<div class="col-md-12 text-center mt-2 p-2">
									<button type="button" data-type="review" class="btn btn-outline-primary btn-save review-btn">確認する</button>
									<button type="button" data-type="register" class="btn btn-outline-primary btn-save register-btn" style="display:none;">回答を登録する</button>
								</div>	
								
						</div>

					</form>


				</div>
			</div>
		</div>
	</div>
@endsection

@section('script')


<script type="text/javascript">

	var review = false;

	$(".btn-save").on('click', function(e){
		 e.preventDefault(e);
		var type = $(this).data('type');

		$('.error-div').hide();

		if(type == 'review'){
			
			if(review==false){ //show are you sure etc.
				$('.review-div').show();
				$('.register-btn').show();
				$('.review-btn').text('変更する');
				$('.answering-div').hide();
				//disable fields here
				$("#exam_form input[type=radio]").attr('disabled', true);
				$("#exam_form input[type=radio]").parent().addClass("options-disabled");
				review = true;
			}else{ //hide
				$('.review-btn').text('確認する');
				$('.review-div').hide();
				$('.register-btn').hide();
				$('.answering-div').show();
				
				//enable fields here
				$("#exam_form input[type=radio]").attr('disabled', false);
				$("#exam_form input[type=radio]").parent().removeClass("options-disabled");
				review = false;
			}

			return false;
		}

		$("#exam_form input[type=radio]").attr('disabled', false); //re enable radio before submit
		const data = $('#exam_form').serialize();
	    $.ajax({
		    	type:"POST",
		        url: "{{ route('seminar_exam.store') }}",
		        data:data,
		        cache:false,
		        beforeSend:function(){
		           	$(".register-btn").prop('disabled', true);
		        },
		    	success:function(response){
		        
		        $(".register-btn").prop('disabled', false);
		     	
		     	review = false;

		        if(response.status == true){
		           	window.location = response.redirect;
		        }else{

		        	if(response.type=='answer_all'){
		        		$('.review-div').hide();
						$('.register-btn').hide();
					
		        		$('.error-div').text('全ての問題を解答してください');
	        	 		$('.error-div').show();
		        	}else if(response.type=='answered'){
		        		window.location = response.redirect;
		        	}
		        }		        
		    },
		    error:function(error){
		        console.log(error);
		        $(".register-btn").prop('disabled', false);
		    }
		});
	});


</script>

@endsection

resources/views/Exam/success.blade.php
@extends('Layout.qrcode.app')
@section('title', '今後の講座 予定')
@section('css')

<style>
	

</style>
@endsection

@section('content')
	<div class="row justify-content-center" style="margin-top: 165px;">
		<div class="col-md-5 col-12">
            <div class="card">
				<div class="card-body text-primary">
					<div class="row pr-4 pl-4">
						<div class="col-md-4 col-4">
							<i class="fa fa-user fa-3x"></i>
						</div>
						<div class="col-md-8 col-8 mt-2">
							<h4 class="font-weight-bold">{{ $user->l_name }} {{ $user->f_name }}</h4>
						</div>
						
					</div>

					
					<div class="row pr-4 pl-4 mt-2">
						<div class="col-md-12 col-12 mt-2">
							<p>セミナー番号{{ $seminar->category_no }} </p>
							<p>	総論 {{ $seminar->category_no }} {{ $seminar->category_name }}</p>
						</div>

						<div class="col-md-12 text-center">
							
							<i class="fas fa-check" style="font-size: 100px;"></i>
							<p> 回答を受け付けました.</p>

						</div>	

						<div class="col-md-12 col-12 mt-2 text-center">
							<p>退席時も忘れずに　会場の出口にて<span class="text-danger">QRコード退出登録</span>をしてください.</p>
							<a href="{{route('seminar.user.detail',$seminar_registration->id)}}" class="btn btn-outline-primary">講座詳細へ戻る</a>
						</div>

					</div>



				</div>
			</div>
		</div>
	</div>
@endsection

@section('script')


<script type="text/javascript">


</script>

@endsection