routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SeminarController;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\SeminarVideoController;
use App\Http\Controllers\SeminarCertificateController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('Auth.index');
})->name('login');

Route::get('/', function () {
    return view('Auth.register');
})->name('registration');

Route::controller(UserController::class)->group(function () {
	Route::get('registration-verify/{token}','showVerifyEmail')->name('registration_verify.get');
	Route::post('registration','store')->name('registration.store');
    Route::get('registration-success', 'success')->name('registration.success');
});

//Authentications/Login
Route::group(['prefix'=> 'auth'], function(){
	Route::name('auth.')->group(function () {
		// For Login
		Route::controller(AuthController::class)->group(function () {
	 		 Route::post('request', 'authenticate')->name('authenticate');
	 		 Route::get('test', 'test')->name('test');
		});

		// For Forgot Password
		Route::controller(ForgotPasswordController::class)->group(function () {
			Route::get('forget-password', 'index')->name('forget.password.get');
			Route::post('forget-password','store')->name('forget.password.post');
			Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
			Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
			Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
			Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
		});
	});
});


// Route::get('account/', 'AccountController@index')->name('account.index');

Route::group(['prefix'=> 'account', 'middleware' => ['auth']], function(){
    Route::name('account.')->group(function () {
        // Main Manager Page
        Route::controller(AccountController::class)->group(function () {
            Route::get('','index')->name('index');
            Route::get('show/{id?}','showUserAccount')->name('show');
            Route::get('edit/{id?}','editUserAccount')->name('edit');
            Route::post('update/{id?}','update')->name('update');

            Route::post('account/certificate/','uploadCertificate')->name('upload.certificate');
        });
    });


    Route::name('qrcode.')->group(function () {
        // QRcode
        Route::controller(QrCodeController::class)->group(function () {
            Route::get('qrcode-details/{id}/{seminar_id}','index')->name('index');
            Route::get('check-reception/{id}','checkSeminar')->name('check.seminar');
            Route::get('error-reception/{id}','errorSeminar')->name('error.seminar');
            Route::get('in-reception/{id}','inSeminar')->name('in.seminar');
            Route::get('out-reception/{id}','outSeminar')->name('out.seminar');
        });
    });

    Route::name('seminar.')->group(function () {
        // Seminar Pages
        Route::controller(SeminarController::class)->group(function () {
            Route::get('seminar-list/{seminar_group_id}','index')->name('index'); //this would be seminar list
            Route::get('seminar-detail/{id}','show')->name('show');  //this would be seminar detail
            Route::post('seminar-register','register')->name('register');  //this would be seminar registration
            Route::post('seminar-cancel','cancel')->name('cancel');  //this would be cancel of seminar registration
            Route::get('seminar-register-action', 'register_action')->name('register.action');

            Route::get('seminar-user-detail/{id}','user_detail')->name('user.detail');  //this would be user seminar detail

        });
    });

    Route::name('seminar_exam.')->group(function () {
        // Seminar Exam
        Route::controller(ExamController::class)->group(function () {
            Route::get('seminar-exam/{seminar_registration_id}','index')->name('index');
            Route::post('seminar-exam-store/','store')->name('store');
            Route::get('seminar-exam-success/{seminar_registration_id}','success')->name('success');
            Route::post('seminar-on-demand-exam-store/','userOnDemandExamstore')->name('user_on_demand_exam.store');
        });
    });


    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

});

// video on demand
Route::group(['prefix'=> 'seminar-video', 'as' => 'SeminarVideo.', 'middleware' => ['auth']], function(){
    Route::controller(SeminarVideoController::class)->group(function () {
        Route::get('','index')->name('index');
        Route::get('start-video/{seminar_id}','start_video')->name('start');
        Route::get('save-video/{seminar_id}','save_video')->name('save.video');
        Route::get('play-video/{user_ondemand_history_id}','play_video')->name('play.video');
        Route::get('exam/{user_ondemand_history_id}/{video_finished}','exam')->name('exam');

        Route::get('course-result/{seminar_id}/{seminar_type}','course_result')->name('course.result');
    });
});

// Certificate
// Route::group(['prefix'=> 'certificate', 'as' => 'certificate.', 'middleware' => ['auth']], function(){
//     Route::controller(SeminarCertificateController::class)->group(function () {
//         Route::get('pdf/Certificate', 'pdfCertificate')->name('certificate.pdf');
//     });
// });

app/Models/Seminar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Seminar extends Model
{
    use HasFactory;
    protected $primaryKey = 'id';
    
    protected $table = 'm_seminars';

    protected $fillable = [
        'm_seminar_group_id',
        'category_no',
        'category_name',
        'seminar_title',
        'seminar_hours',
        'start_at',
        'end_at',
        'capacity',
        'seminar_date',
        'reception_open_at',
        'reception_close_at',
        'teacher_name',
        'teacher_affiliation1',
        'teacher_affiliation2',
        'teacher_affiliation3',
        'place',
        'movie_url',
    ];

    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];

    protected $dates = [
        'start_at',
        'end_at',
        'reception_open_at',
        'reception_close_at',

    ];
    
    public function seminarGroup(){
        return $this->belongsTo('App\Models\SeminarGroup', 'm_seminar_group_id', 'id');
    }

    public function exams(){
        return $this->hasMany('App\Models\Exam', 'm_seminar_id', 'id');
    }

    public function video()
    {
        return $this->hasOne(SeminarVideo::class, 'm_seminar_id');
    }

}

app/Http/Controllers/SeminarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Validator;
use Carbon\Carbon;

use App\Models\User;
use App\Models\Seminar;
use App\Models\SeminarGroup;
use App\Models\SeminarRegistration;
use App\Models\UserSeminarStatus;
use App\Models\UserExam;

class SeminarController extends Controller
{
    public function index($seminar_group_id){

       //seminar list
       if($seminar_group_id){
            $today_date = Carbon::now();
            $seminar_group = SeminarGroup::with(["seminars" => function($q){
                    $q->orderBy('category_no');
                }])->where('id',$seminar_group_id)->first();
            
            //return $seminar_group;
            return view('Seminar.index',compact('seminar_group','today_date'));
       }
    }

    public function show($id){ //seminar detail
      $user = Auth::user();
      $seminar = Seminar::find($id);
      $capacity_left = capacity_left($id);
      //check if the user already register on the event
      $with_registration = SeminarRegistration::where('user_id',$user->id)->where('m_seminar_id',$id)->whereNull('canceled_at');
      return view('Seminar.detail' ,compact('seminar','capacity_left','with_registration'));
    }

    public function register(Request $request){ //seminar registration
      $user = Auth::user();
      $group_id = $request->get('group_id');
      $seminar_id = $request->get('seminar_id');

      $capacity = capacity_left($seminar_id);

      $check_duplicate = SeminarRegistration::where('user_id',$user->id)->where('m_seminar_group_id',$group_id)->where('m_seminar_id',$seminar_id)->whereNull('canceled_at')->count();

      if($check_duplicate > 0){
        return response()->json(['status' => false, 'type' => 'duplicate']);
      }else{
        if($capacity >= 1){
          return response()->json(['status' => false, 'type' => 'capacity_full', 'redirect' => route('seminar.register.action',['seminar_id' => $seminar_id,'message' => '既に定員に達しているため、申込できませんでした'])]);
        }else{
          $data = new SeminarRegistration;
          $data->m_seminar_group_id = $group_id;
          $data->m_seminar_id = $seminar_id;
          $data->user_id = $user->id;
          $data->registration_at = Carbon::now();
          if($data->save()){
            $qr_code = $user->id.','.$group_id.','.$seminar_id.','.$data->id;
            $data->qr_code = $qr_code;
            $data->save();
            $action = 'success';
            return response()->json(['status' => true, 'redirect' => route('seminar.register.action',['seminar_id' => $seminar_id,'message' => '下記セミナーへの申込を行いました'])]);
          }
        }
      }
    }

    public function cancel(Request $request){ //seminar cancelation
      $user = Auth::user();
      $seminar_registration_id = $request->get('seminar_registration_id');
      $update = SeminarRegistration::where('user_id',$user->id)->where('id',$seminar_registration_id)->update(['canceled_at' => Carbon::now()]);

      if($update){
        $seminar_id = $request->get('seminar_id');
        return response()->json(['status' => true, 'redirect' => route('seminar.register.action',['seminar_id' => $seminar_id,'message' => '下記セミナーへの申込をキャンセルしました'])]);
      }
    }

    function register_action(Request $request){
      $seminar = Seminar::find($request->seminar_id);
      $message = $request->message;
      return view('Seminar.register_action',compact('seminar','message'));
    }

    public function user_detail($id){ //seminar detail

      $user = Auth::user();
      $seminar_registration = SeminarRegistration::where('id',$id)->where('user_id',$user->id)->whereNull('canceled_at')->first();

      if($seminar_registration){
        
        $seminar = Seminar::find($seminar_registration->m_seminar_id);
        //check if the user data in user_seminar_status
        $user_seminar_status = UserSeminarStatus::where('seminar_registration_id',$seminar_registration->id);

        //user exam
        $seminar_id = $seminar_registration->m_seminar_id;
        $user_exams = UserExam::whereHas('exam_info', function ($query) use($seminar_id) {
                                          $query->where('m_seminar_id',$seminar_id);})->where('seminar_registration_id',$seminar_registration->id)->where('user_id',$user->id)->get();
        
        return view('Seminar.user_seminar_detail' ,compact('seminar','user_seminar_status','seminar_registration','user_exams'));
      }else{
        return redirect()->route('account.index');
      }

    }
}

resources/views/Seminar/detail.blade.php
@extends('Layout.account.app')
@section('title', '今後の講座 予定')

@section('css')
<style type="text/css">

</style>
@endsection

@section('content')
<div class="row justify-content-center mt-5">
   <div class="col-md-5 col-12">
      <div class="row">
         <div class="col-sm-12 col-12">
            <div class="text-primary">
               <div class="row mb-2">
                  <div class="col-4">
                     <i class="fa fa-calendar-alt"> 日  程 </i>
                  </div>
                  <div class="col-8">
                     <b class="">{{ japan_date($seminar->seminar_date) }}</b>
                  </div>
               </div>
               <div class="row mb-2">
                  <div class="col-4">
                     <i class="fa fa-clock"> 開催時間</i>
                  </div>
                  <div class="col-8">
                     <b class="">{{ ltrim($seminar->start_at->format('H:i'),"0")." ~ ".ltrim($seminar->end_at->format('H:i'),"0") }}</b>
                  </div>
               </div>
               <div class="row mb-2">
                  <div class="col-4">
                     <i class="fa fa-pencil-alt"> 受講枠</i>
                  </div>
                  <div class="col-8">
                     <p class="mb-0">セミナー番号{{ $seminar->category_no }} 領域{{ $seminar->category_no }} <br>({{ $seminar->category_name }}) / {{ $seminar->seminar_title }}</p>
                  </div>
               </div>
               <div class="row mb-2">
                  <div class="col-4">
                     <i class="text-primary fa fa-mobile-alt"> 受付時間</i>
                  </div>
                  <div class="col-8">
                     <p class="mb-0">{{ japan_date($seminar->seminar_date,'md') }} {{ ltrim($seminar->reception_open_at->format('H:i'),"0")." ~ ".ltrim($seminar->reception_close_at->format('H:i'),"0") }}</p>
                  </div>
               </div>
               @if($capacity_left >= 0.9)
	               <div class="row p-4">
	                  <div class="col text-center">
	                     <b class="text-danger"> 既に定員に達しています</b>
	                  </div>
	               </div>
               @endif
            </div>
            <input type="hidden" id="group_id" name="group_id" value="{{ $seminar->m_seminar_group_id }}">
            <input type="hidden" id="seminar_id" name="seminar_id" value="{{ $seminar->id }}">
            <input type="hidden" id="seminar_registration_id" name="seminar_registration_id" value="{{ ($with_registration->count() > 0) ? $with_registration->first()->id : '' }}">
            <div class="row">
               <div class="col">
                  <a type="button" class="btn btn-light border-primary btn-block text-primary"  href="{{ route('seminar.index',$seminar->m_seminar_group_id) }}" style="font-size: 14px">セミナー一覧へ戻る</a>
               </div>
               <div class="col">
                  @if($with_registration->count() > 0)
                  	<button type="button" class="text-sm btn btn-light border-primary btn-block text-danger" data-url="{{ route('seminar.cancel') }}" id="btn_cancel">申込キャンセル</button>
                  @else
                     @if(capacity_left($seminar->id) >= 1)
                        <button type="button" class="text-sm btn btn-light border-primary btn-block text-primary" disabled="">参加申込</button>
                     @else
                        <button type="button" class="text-sm btn btn-light border-primary btn-block text-primary" data-url="{{ route('seminar.register') }}" id="btn_register">参加申込</button>
                     @endif
                  @endif
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

@endsection

@section('script')
<script type="text/javascript" src="{{asset('js/seminar_registration.js')}}"></script>
@endsection

resources/views/Seminar/register_action.blade.php
@extends('Layout.account.app')
@section('title', '今後の講座 予定')
@section('css')
@endsection

@section('content')
	<div class="row justify-content-center mt-5">
		<div class="col-md-5 col-12">
            <div class="row">
				<div class="col-sm-12 text-center">
					<label class="page-title">
						{{ $message }}
					</label>
				</div>
				<div class="col-sm-12 col-12 text-center">
					<p class="fs-4 fw-bold"><strong>セミナー番号 {{ $seminar->category_no }} 領域 {{ $seminar->category_no }} <br> {{ $seminar->category_name }}</strong></p>
				</div>
         		<div class="col-sm-12 text-right"> 
         			{{-- <a type="button" class="btn btn-light border-primary text-primary float-end"  href="{{ route('seminar.show',$seminar->m_seminar_group_id) }}">戻る</a> --}}
         			<a type="button" class="btn btn-light border-primary text-primary float-end"  href="{{ URL::previous() }}">戻る</a>
         		</div>
			</div>
		</div>
	</div>
@endsection

resources/views/Seminar/user_seminar_detail.blade.php
@extends('Layout.account.app')
@section('title', 'セミナー詳細')

@section('css')
@endsection

@section('content')
<div class="row justify-content-center mt-5">
   <div class="col-md-5 col-12">
      <div class="row">
         <div class="col-sm-12 col-12">
            <div class="text-primary">
               <div class="row mb-2">
                  <div class="col-4">
                     <i class="fa fa-calendar-alt"> 日  程 </i>
                  </div>
                  <div class="col-8">
                     <b class="">{{ japan_date($seminar->seminar_date) }}</b>
                  </div>
               </div>
               <div class="row mb-2">
                  <div class="col-4">
                     <i class="fa fa-clock"> 開催時間</i>
                  </div>
                  <div class="col-8">
                     <b class="">{{ $seminar->start_at->format('g:i')." ~ ".$seminar->end_at->format('g:i') }}</b>
                  </div>
               </div>
               <div class="row mb-2">
                  <div class="col-4">
                     <i class="fa fa-pencil-alt"> 受講枠</i>
                  </div>
                  <div class="col-8">
                     <p class="mb-0">セミナー番号{{ $seminar->category_no }} 総論{{ $seminar->category_no }} ({{ $seminar->category_name }})</p>
                  </div>
               </div>
               <div class="row mb-2">
                  <div class="col-4">
                     <i class="text-primary fa fa-mobile-alt"> 受付時間</i>
                  </div>
                  <div class="col-8">
                     <p class="mb-0">{{ japan_date($seminar->seminar_date,'md') }} {{ $seminar->reception_open_at->format('g:i')." ~ ".$seminar->reception_close_at->format('g:i') }}</p>
                  </div>
               </div>

               @if($user_seminar_status->count() == 0 || (!empty($user_seminar_status->first()->exam_answered_at) && empty($user_seminar_status->first()->reception_out_at)) )
                  <div class="row p-4">
                     <div class="col text-center">
                       <b class="text-danger"> QRコードで参加受付を行ってください</b>
                     </div>
                  </div>
               @endif

               @if($seminar->reception_open_at > now())
                  <div class="row mb-3">
                     <div class="col text-center">
                       <b class="text-danger"> 受付開始日時までお待ちください</b>
                     </div>
                  </div>
               @else
                  <div class="row mb-3">
                     <div class="col text-center">
                        @if($user_seminar_status->count() == 0)
                           <button type="button" class="text-sm btn btn-primary btn-block">参加受付</button>
                        @else
                           <button type="button" class="text-sm btn btn-light btn-block text-primary">参加受付</button>
                        @endif
                     </div>
                     <div class="col text-center">
                        @if(!empty($user_seminar_status->first()->reception_in_at) && empty($user_seminar_status->first()->exam_answered_at))
                           <button type="button" class="text-sm btn btn-primary border-0 btn-block">テスト回答</button>
                        @else
                           <button type="button" class="text-sm btn btn-light border-0 btn-block text-primary">テスト回答</button>
                        @endif
                     </div>
                     <div class="col text-center">
                        @if(!empty($user_seminar_status->first()->exam_answered_at) && empty($user_seminar_status->first()->reception_out_at))
                           <button type="button" class="text-sm btn btn-primary border-0 btn-block">退席確認</button>
                        @else
                           <button type="button" class="text-sm btn btn-light border-0 btn-block text-primary">退席確認</button>
                        @endif
                     </div>
                  </div>

                  <div class="row mb-3">
                     <div class="col text-center">
                     @if($user_seminar_status->count() == 0)
                        <i class="fas fa-exclamation-circle fa-3x text-info"></i>
                     @else
                        <i class="fas fa-check-circle fa-3x text-secondary"></i>
                     @endif
                     </div>
                     <div class="col text-center">
                       <button class="btn btn-sm text-info"><i class="fas fa-arrow-right fa-3x"></i></button>
                     </div>
                     <div class="col text-center">
                        @if(!empty($user_seminar_status->first()->reception_in_at) && empty($user_seminar_status->first()->exam_answered_at))
                           <i class="fas fa-exclamation-circle fa-3x text-info"></i>
                        @elseif(!empty($user_seminar_status->first()->reception_in_at) && !empty($user_seminar_status->first()->exam_answered_at))
                           <i class="fas fa-check-circle fa-3x text-secondary"></i>
                        @else
                           <i class="fas fa-times-circle fa-3x text-secondary"></i>
                        @endif
                     </div>
                     <div class="col text-center">
                       <button class="btn btn-sm text-info"><i class="fas fa-arrow-right fa-3x"></i></button>
                     </div>
                     <div class="col text-center">
                        @if(!empty($user_seminar_status->first()->exam_answered_at) && empty($user_seminar_status->first()->reception_out_at))
                           <i class="fas fa-exclamation-circle fa-3x text-info"></i>
                        @elseif(!empty($user_seminar_status->first()->exam_answered_at) && !empty($user_seminar_status->first()->reception_out_at))
                           <i class="fas fa-check-circle fa-3x text-secondary"></i>
                        @else
                           <i class="fas fa-times-circle fa-3x text-secondary"></i>
                        @endif
                     </div>
                  </div>
                  
                  @if($user_seminar_status->count() == 0)

                  <div class="row mb-3">
                     <div class="col text-center">
                       <a href="{{ route('qrcode.index',[$seminar_registration->id,$seminar->id]) }}" class="btn btn-primary w-50">QRコード</a>
                     </div>
                  </div>
                  <div class="row mb-3">
                     <div class="col text-center">
                       QRコードで参加受付を行ってください
                     </div>
                  </div>

                  <div class="row mb-3">
                     <div class="col text-center">
                       <button disabled="" class="btn btn-secondary w-50"> テスト回答 </button>
                     </div>
                  </div>
                  <div class="row mb-3">
                     <div class="col text-center text-secondary">
                       まだ受付登録が完了していません
                     </div>
                  </div>
               @elseif(!empty($user_seminar_status->first()->reception_in_at) && empty($user_seminar_status->first()->exam_answered_at))

                  <div class="row mb-3">
                     <div class="col text-center">
                       <a href="{{ route('seminar_exam.index',$seminar_registration->id)}}" class="btn btn-primary w-50"> テスト回答 </a>
                     </div>
                  </div>
                  <div class="row mb-3">
                     <div class="col text-center text-secondary">
                       テスト回答ボタンよりテストを受けてください
                     </div>
                  </div>

               @elseif(!empty($user_seminar_status->first()->exam_answered_at) && empty($user_seminar_status->first()->reception_out_at))

                  <div class="row mb-3">
                     <div class="col text-center">
                       <a href="{{ route('qrcode.index',[$seminar_registration->id,$seminar->id]) }}" class="btn btn-primary w-50">QRコード</a>
                     </div>
                  </div>
                  <div class="row mb-3">
                     <div class="col text-center">
                       QRコードで退席確認を行ってください
                     </div>
                  </div>
               @else
               <div class="row mb-3"></div>
               @endif

               <div class="row mb-3">
                  <div class="col-3 text-center">
                     <hr>
                  </div>
                  <div class="col-6 text-center text-secondary">
                    ご登録の回答内容
                  </div>
                  <div class="col-3 text-center">
                    <hr>
                  </div>
               </div>

               <!-- Questions here -->
               <div class="row text-center">
                  @forelse ($user_exams as $user_exam)
                     <div class="col">
                        <p class="text-center">問題 {{ $user_exam->exam_info->question_no }}</p>
                        <button type="button" class=" btn btn-block {{ ($user_exam->answer == 1) ? 'btn-primary' : 'btn-light text-primary' }}" >はい</button>
                        <button type="button" class=" btn btn-block {{ ($user_exam->answer == 0) ? 'btn-primary' : 'btn-light text-primary' }}">いいえ</button>
                     </div>
                  @empty
                     @for ($i = 0; $i < 3; $i++)
                        <div class="col-4">
                           <p class="text-center">問題 {{ $i + 1 }}</p>
                           <button type="button" class=" btn btn-block btn-secondary">&nbsp;</button>
                           <button type="button" class=" btn btn-block btn-secondary">&nbsp;</button>
                        </div>
                     @endfor
                  @endforelse
               </div>

               @endif

            </div>
         </div>

         <div class="col-sm-12 text-center mt-3">
            <a href="{{route('seminar.index',$seminar->m_seminar_group_id)}}" class="btn btn-primary">戻る</a>
         </div>

      </div>
   </div>
</div>

@endsection

@section('script')
@endsection